server:
  port: 8881
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/omnipotence?characterEncoding=utf-8&useOldAliasMetadataBehavior=true&&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 6000
mybatis:
  mapper-locations: classpath:/mappers/**.xml

